include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'
  
stages:
  - build

build:
  image: docker:26.1.4
  stage: build
  services:
    - docker:26.1.4-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG